# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://uvis-tor.com.ua # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: true # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              required: false,
            }
          - {
              label: Subtitle,
              name: subtitle,
              widget: markdown,
              required: false,
            }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: "Addresses"
            name: "addresses"
            widget: "list"
            fields:
              - { label: Address, name: address, widget: text }
              - { label: Phone, name: phone, widget: string }
          - { label: Email Address, name: email, widget: string }

      - file: "content/pages/blog.md"
        label: "Equipment Page"
        name: "equipment-page"
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              required: false,
            }
          - {
              label: Subtitle,
              name: subtitle,
              widget: markdown,
              required: false,
            }
          - { label: Body, name: body, widget: markdown, required: false }

      - file: "content/pages/gallery.md"
        label: "Gallery"
        name: "gallery-page"
        editor:
          preview: true
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Subtitle,
              name: subtitle,
              widget: markdown,
              required: false,
            }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              required: false,
            }
          - label: "Photo Gallery"
            name: "photoGallery"
            widget: "list"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Images"
                name: "images"
                widget: "list"
                field: { widget: image }

      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - {
              label: Subtitle,
              name: subtitle,
              widget: markdown,
              required: false,
            }
          - { label: Body, name: body, widget: markdown, required: false }

      - file: "content/pages/benefits.md"
        label: "Benefits"
        name: "benefits-page"
        editor:
          preview: true
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              required: false,
            }
          - {
              label: Subtitle,
              name: subtitle,
              widget: markdown,
              required: false,
            }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: "Benefits"
            name: "benefits"
            widget: "list"
            fields:
              - { label: Benefit, name: benefit, widget: markdown }
              - { label: Image, name: image, widget: image }

  - name: equipments
    label: Equipment
    editor:
    preview: true
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Title, name: title, widget: string }
      - {
          label: Equipment Featured Image,
          name: equipmentFeaturedImage,
          widget: image,
          required: false,
        }
      - { label: Content, name: body, widget: markdown, required: false }
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        fields:
          - label: "Category"
            name: "category"
            widget: "relation"
            collection: "equipmentCategories"
            searchFields: ["title"]
            valueField: "title"
      - label: "Photo Gallery"
        name: "photoGallery"
        widget: "list"
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Images"
            name: "images"
            widget: "list"
            field: { widget: image }

  - name: equipmentCategories
    label: Equipment Category
    editor:
      preview: false
    folder: content/equipmentCategories
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Title, name: title, widget: string }

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - {
                  label: Twitter,
                  name: twitter,
                  widget: string,
                  required: false,
                }
              - {
                  label: Instagram,
                  name: instagram,
                  widget: string,
                  required: false,
                }
              - {
                  label: Facebook,
                  name: facebook,
                  widget: string,
                  required: false,
                }
              - {
                  label: VKontakte,
                  name: vkontakte,
                  widget: string,
                  required: false,
                }
              - {
                  label: WhatsApp,
                  name: whatsapp,
                  widget: string,
                  required: false,
                }
              - {
                  label: WhatsApp Message,
                  name: whatsappMessage,
                  widget: string,
                  required: false,
                }
          - {
              label: Header Meta / Scripts,
              name: headerScripts,
              widget: text,
              required: false,
            }
          - {
              label: Enable Service Worker Pre-Cache,
              name: enableServiceWorker,
              widget: boolean,
              required: false,
            }
